package io.learn.lexigeek.common.validation;

public enum ErrorCodes {
    //ACCOUNT
    EMAIL_ALREADY_EXISTS,
    USER_NOT_FOUND,

    //LANGUAGE
    LANGUAGE_NOT_FOUND,

    //CATEGORY
    CATEGORY_NOT_FOUND,
    PARENT_CATEGORY_NOT_FOUND,
    CATEGORY_CIRCULAR_REFERENCE_ERROR,

    //WORD
    WORD_NOT_FOUND,
    WORD_ALREADY_ACCEPTED,
    WORD_PART_INVALID,

    //GENERAL
    EXTERNAL_SERVICE_ERROR,
    GENERAL_ERROR,
    INTERNAL_SERVER_ERROR,
    PAGEABLE_REQUEST_TOO_LARGE,
    VALIDATION_ERROR,

    //SECURITY
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
}
