--liquibase formatted sql
--changeset marcin.kaczor:1 labels:LG-1

CREATE TABLE "accounts"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid     UUID UNIQUE  NOT NULL,
    username VARCHAR(20)  NOT NULL,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(72)  NOT NULL
);

--rollback DROP TABLE "accounts";
