--liquibase formatted sql
--changeset marcin.kaczor:2 labels:LG-2

CREATE TABLE "languages"
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                UUID UNIQUE  NOT NULL,
    name                VARCHAR(20)  NOT NULL,
    shortcut            VARCHAR(10)  NOT NULL,
    code_for_speech     VARCHAR(10)  NOT NULL DEFAULT '',
    code_for_translator VARCHAR(10)  NOT NULL DEFAULT '',
    public              BOOLEAN      NOT NULL DEFAULT true,
    special_letters     VARCHAR(255) NOT NULL DEFAULT '',
    account_id          BIGINT       NOT NULL
        CONSTRAINT fk_languages_account_id REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_languages_shortcut ON languages (shortcut);
CREATE INDEX IF NOT EXISTS idx_languages_account_id ON languages (account_id);

--rollback DROP TABLE "languages";