--liquibase formatted sql
--changeset marcin.kaczor:2 labels:LG-2

CREATE TABLE "languages"
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid              UUID UNIQUE  NOT NULL,
    name              VARCHAR(20)  NOT NULL,
    shortcut          VARCHAR(10)  NOT NULL,
    code_for_speech     VARCHAR(10)  NOT NULL DEFAULT '',
    code_for_translator VARCHAR(10)  NOT NULL DEFAULT '',
    hidden            BOOLEAN      NOT NULL DEFAULT false,
    special_letters    VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE INDEX idx_languages_shortcut ON languages(shortcut);

--rollback DROP TABLE "languages";