--liquibase formatted sql
--changeset marcin.kaczor:3 labels:LG-3

CREATE TABLE "categories"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        UUID UNIQUE  NOT NULL,
    parent_id   BIGINT NULL
            CONSTRAINT fk_categories_category_parent_id REFERENCES categories (id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    mode        VARCHAR(10)  NOT NULL CHECK (mode IN ('DICTIONARY', 'EXERCISE')),
    method      VARCHAR(18)  NOT NULL CHECK (method IN ('QUESTION_TO_ANSWER', 'ANSWER_TO_QUESTION', 'BOTH')),
    position    INTEGER      NOT NULL,
    language_id BIGINT       NOT NULL
        CONSTRAINT fk_categories_language_id REFERENCES languages (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_categories_category_parent_id ON categories (parent_id);
CREATE INDEX IF NOT EXISTS idx_categories_language_id ON categories (language_id);
CREATE INDEX IF NOT EXISTS idx_categories_uuid ON categories (uuid);

--rollback DROP TABLE "categories";