--liquibase formatted sql
--changeset marcin.kaczor:4 labels:LG-4

CREATE TABLE "words"
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               UUID UNIQUE                 NOT NULL,
    accepted           BOOLEAN                     NOT NULL DEFAULT FALSE,
    chosen             BOOLEAN                     NOT NULL DEFAULT FALSE,
    comment            TEXT                        NULL,
    created            TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mechanism          VARCHAR(5)                  NOT NULL CHECK (mechanism IN ('BASIC', 'TABLE')),
    reset_time         TIMESTAMP WITHOUT TIME ZONE NULL
);

CREATE INDEX IF NOT EXISTS idx_words_accepted ON words (accepted);
CREATE INDEX IF NOT EXISTS idx_words_chosen ON words (chosen);
CREATE INDEX IF NOT EXISTS idx_words_mechanism ON words (mechanism);

CREATE TABLE "category_word"
(
    category_id BIGINT NOT NULL
        CONSTRAINT fk_category_word_category_id REFERENCES categories (id) ON DELETE CASCADE,
    word_id     BIGINT NOT NULL
        CONSTRAINT fk_category_word_word_id REFERENCES words (id) ON DELETE CASCADE,
    PRIMARY KEY (category_id, word_id)
);

CREATE TABLE "word_parts"
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           UUID UNIQUE NOT NULL,
    answer         BOOLEAN     NOT NULL DEFAULT FALSE,
    basic_word     TEXT        NULL,
    position       INTEGER     NOT NULL,
    to_speech      BOOLEAN     NOT NULL DEFAULT FALSE,
    separator      BOOLEAN     NOT NULL DEFAULT FALSE,
    separator_type VARCHAR(10) NULL CHECK (separator_type IN ('ENTER', 'TAB', 'MULTI_DASH')),
    word           TEXT        NULL,
    word_id        BIGINT      NOT NULL
        CONSTRAINT fk_word_parts_word_id REFERENCES words (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_word_parts_word_id ON word_parts (word_id);
CREATE INDEX IF NOT EXISTS idx_word_parts_word_id_position ON word_parts (word_id, position);
CREATE INDEX IF NOT EXISTS idx_word_parts_uuid ON word_parts (uuid);

CREATE TABLE "word_stats"
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid      UUID UNIQUE NOT NULL,
    answered  INTEGER     NOT NULL DEFAULT 0,
    to_answer INTEGER     NOT NULL DEFAULT 0,
    method    VARCHAR(18) NOT NULL CHECK (method IN ('QUESTION_TO_ANSWER', 'ANSWER_TO_QUESTION', 'BOTH')),
    word_id   BIGINT      NOT NULL
        CONSTRAINT fk_word_stats_word_id REFERENCES words (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_word_stats_word_id ON word_stats (word_id);
CREATE INDEX IF NOT EXISTS idx_word_stats_uuid ON word_stats (uuid);

--rollback DROP TABLE "word_stats";
--rollback DROP TABLE "word_parts";
--rollback DROP TABLE "category_word";
--rollback DROP TABLE "words";
