--liquibase formatted sql
--changeset marcin.kaczor:6 labels:LG-6

CREATE TABLE "viewed_public_words"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL
        CONSTRAINT fk_viewed_public_words_account_id REFERENCES accounts (id) ON DELETE CASCADE,
    word_id    BIGINT NOT NULL
        CONSTRAINT fk_viewed_public_words_word_id REFERENCES words (id) ON DELETE CASCADE,
    viewed_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (account_id, word_id)
);

CREATE INDEX IF NOT EXISTS idx_viewed_public_words_account_id ON viewed_public_words (account_id);
CREATE INDEX IF NOT EXISTS idx_viewed_public_words_word_id ON viewed_public_words (word_id);

--rollback DROP TABLE "viewed_public_words";
