--liquibase formatted sql
--changeset marcin.kaczor:10 labels:LG-11

CREATE TABLE activities
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid          UUID                        NOT NULL UNIQUE,
    created       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type          VARCHAR(30)                 NOT NULL,
    language_name VARCHAR(255)                NOT NULL,
    category_name VARCHAR(255)                NOT NULL,
    account_id    BIGINT                      NOT NULL
        CONSTRAINT fk_activities_account REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE INDEX idx_activities_account ON activities (account_id);
CREATE INDEX idx_activities_created ON activities (created);
CREATE INDEX idx_activities_type ON activities (type);

--rollback DROP TABLE "activities";
